"use client"

import { useEffect, useRef, useState } from "react"
import Link from "next/link"
import { motion } from "framer-motion"
import { Zap, Lock, ArrowUpRight, Info } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { SignalBadge } from "@/components/ui/signal-badge"
import { Skeleton } from "@/components/ui/skeleton"
import { Button } from "@/components/ui/button"
import { forecastApi } from "@/lib/api"
import { MODEL_METRICS } from "@/lib/model-metrics"
import { useAuthStore } from "@/store/auth-store"
import type { AlphaSignal } from "@/types"

// Server-side pollers re-run hourly; 5 min on the client keeps the UI fresh
// without hammering the DB. A user who leaves the tab open won't see stale data.
const REFRESH_INTERVAL_MS = 5 * 60 * 1000

export default function AlphaSignalsPage() {
  const tier = useAuthStore((s) => s.user?.tier ?? "free")
  const [signals, setSignals] = useState<AlphaSignal[]>([])
  const [loading, setLoading] = useState(true)
  const [confidentOnly, setConfidentOnly] = useState(true)
  // `locked` is a *runtime* paywall state — flipped ON when server returns 403,
  // regardless of what the client thinks the tier is. Defends against stale
  // JWT / tampered localStorage. Initial value is false so paywall doesn't
  // flash for Pro/Premium users during hydration (Zustand store is empty on
  // first render). The server 403 is the source of truth.
  const [locked, setLocked] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [lastUpdate, setLastUpdate] = useState<Date | null>(null)
  // `mounted` avoids a second race: during SSR + first hydration tier is "free"
  // until the Zustand store rehydrates from localStorage. Show skeleton, not
  // paywall, until we've truly read the tier.
  const [mounted, setMounted] = useState(false)
  const abortRef = useRef<AbortController | null>(null)

  useEffect(() => {
    setMounted(true)
  }, [])

  useEffect(() => {
    if (!mounted) return
    if (tier === "free") {
      setLocked(true)
      setLoading(false)
      return
    }

    let cancelled = false

    async function load(initial: boolean) {
      // Cancel in-flight request if user toggles confident_only mid-fetch
      abortRef.current?.abort()
      const controller = new AbortController()
      abortRef.current = controller

      if (initial) setLoading(true)
      try {
        const { data } = await forecastApi.getAlphaSignals({
          limit: 50,
          confident_only: confidentOnly,
        })
        if (cancelled) return
        setSignals(data)
        setLocked(false)
        setError(null)
        setLastUpdate(new Date())
      } catch (err: unknown) {
        if (cancelled) return
        const e = err as { response?: { status?: number; data?: { detail?: string } }; code?: string }
        if (e.code === "ERR_CANCELED") return
        if (e.response?.status === 403) {
          setLocked(true)
        } else {
          setError(e.response?.data?.detail ?? "Failed to load Alpha Signals")
        }
      } finally {
        if (!cancelled) setLoading(false)
      }
    }

    load(true)
    const id = setInterval(() => load(false), REFRESH_INTERVAL_MS)
    return () => {
      cancelled = true
      clearInterval(id)
      abortRef.current?.abort()
    }
  }, [tier, confidentOnly, mounted])

  if (locked) {
    return <AlphaSignalsPaywall />
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <div className="mb-2 flex items-center gap-2">
            <Zap className="size-5 text-[var(--accent-from)]" />
            <h1 className="font-heading text-2xl font-semibold">Alpha Signals</h1>
            <Badge variant="default" className="text-[10px]">Pro</Badge>
          </div>
          <p className="max-w-2xl text-sm text-text-secondary">
            High-conviction signals generated by a 3-model ensemble (ep2 + ep4 + ep5).
            Historical back-test:{" "}
            <span className="text-success font-medium">Sharpe {MODEL_METRICS.conflong_sharpe}</span>,{" "}
            <span className="text-success font-medium">
              Win Rate {MODEL_METRICS.conflong_win_rate_pct}%
            </span>{" "}
            on {MODEL_METRICS.conflong_n_trades} consensus trades.
          </p>
        </div>
        <div className="flex items-center gap-3">
          {lastUpdate && (
            <span className="text-[11px] text-text-muted">
              Updated {lastUpdate.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
            </span>
          )}
          <button
            onClick={() => setConfidentOnly((x) => !x)}
            className="rounded-button border border-border-subtle bg-bg-surface px-3 py-1.5 text-xs font-medium text-text-secondary hover:bg-bg-elevated hover:text-text-primary transition-colors"
            title="Filter: consensus BUY requires all 3 models to place the lower-80% CI above current price"
          >
            {confidentOnly ? "Consensus BUY only" : "All signals"}
          </button>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="rounded-card border border-border-subtle bg-bg-surface/40 px-4 py-3 text-xs text-text-muted flex items-start gap-2">
        <Info className="size-3.5 shrink-0 mt-0.5" />
        <p>
          Signals expire every 2 hours. Back-test performance based on single test window (post Oct 2024) —
          past performance does not guarantee future results. This is not financial advice.
        </p>
      </div>

      {/* Signal cards */}
      {loading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {Array.from({ length: 9 }).map((_, i) => (
            <Skeleton key={i} className="h-[184px] rounded-card" />
          ))}
        </div>
      ) : error ? (
        <div className="rounded-card border border-danger/20 bg-danger/5 px-5 py-12 text-center text-sm text-danger">
          {error}
        </div>
      ) : signals.length === 0 ? (
        <div className="rounded-card border border-border-subtle bg-bg-surface px-5 py-16 text-center">
          <p className="text-sm text-text-secondary">
            No {confidentOnly ? "high-consensus " : ""}signals right now. Next ensemble run at the top of the hour.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {signals.map((s, i) => (
            <SignalCard key={s.ticker} signal={s} index={i} />
          ))}
        </div>
      )}
    </div>
  )
}

function SignalCard({ signal, index }: { signal: AlphaSignal; index: number }) {
  const consensusColor =
    signal.model_consensus === "HIGH"
      ? "text-success"
      : signal.model_consensus === "MEDIUM"
      ? "text-warning"
      : "text-danger"

  return (
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: Math.min(index * 0.03, 0.3), duration: 0.25, ease: "easeOut" }}
    >
      <Link
        href={`/stocks/${signal.ticker}`}
        className="group block rounded-card border border-border-subtle bg-bg-surface p-4 transition-all duration-150 hover:border-border-hover hover:shadow-[0_0_20px_rgba(0,212,170,0.06)]"
      >
        {/* Row 1: ticker + signal */}
        <div className="flex items-start justify-between">
          <div>
            <div className="flex items-center gap-2">
              <span className="font-mono text-base font-semibold">{signal.ticker}</span>
              {signal.confident_long && (
                <Badge variant="success" className="text-[9px]">
                  Consensus BUY
                </Badge>
              )}
            </div>
            <p className="mt-0.5 font-mono text-xs text-text-muted">
              ${signal.current_close.toFixed(2)}
            </p>
          </div>
          <SignalBadge signal={signal.signal} confidence={signal.confidence} />
        </div>

        {/* Row 2: returns grid */}
        <div className="mt-3 grid grid-cols-3 gap-2 border-t border-border-subtle pt-3">
          <ReturnCell label="1d" value={signal.predicted_return_1d} />
          <ReturnCell label="1w" value={signal.predicted_return_1w} />
          <ReturnCell label="1m" value={signal.predicted_return_1m} />
        </div>

        {/* Row 3: consensus meter — visual representation of how tightly the
            3 ensemble models agree. Filled bars = tight agreement, narrow band.
            Empty bars = wide disagreement, caution warranted. Maps to the
            disagreement tier thresholds in shared/utils.py. */}
        <div className="mt-3">
          <div className="flex items-center justify-between text-[10px] text-text-muted mb-1.5">
            <span>
              Model consensus{" "}
              <span className={`font-medium ${consensusColor}`}>{signal.model_consensus}</span>
            </span>
            <span className="font-mono">σ={(signal.disagreement_score * 100).toFixed(1)}%</span>
          </div>
          <ConsensusMeter tier={signal.model_consensus} />
        </div>

        {/* Row 4: CI range as visual band (helps user feel uncertainty). */}
        <div className="mt-3">
          <div className="flex items-center justify-between text-[10px] text-text-muted mb-1">
            <span>80% confidence range (1d)</span>
            <span className="font-mono">
              ${signal.lower_80_1d.toFixed(2)}–${signal.upper_80_1d.toFixed(2)}
            </span>
          </div>
          <CIRangeBar
            current={signal.current_close}
            lower={signal.lower_80_1d}
            upper={signal.upper_80_1d}
            median={signal.median_1d}
          />
        </div>
      </Link>
    </motion.div>
  )
}

/** Visual consensus meter — 3 pips representing the 3 ensemble models.
 *  HIGH: all 3 lit (tight agreement). MEDIUM: 2 lit (moderate disagreement).
 *  LOW: 1 lit (models diverge — caution). Color-coded. */
function ConsensusMeter({ tier }: { tier: "HIGH" | "MEDIUM" | "LOW" }) {
  const filled = tier === "HIGH" ? 3 : tier === "MEDIUM" ? 2 : 1
  const color =
    tier === "HIGH"
      ? "bg-success"
      : tier === "MEDIUM"
      ? "bg-warning"
      : "bg-danger"

  return (
    <div className="flex gap-1">
      {[0, 1, 2].map((i) => (
        <div
          key={i}
          className={`h-1.5 flex-1 rounded-full ${
            i < filled ? color : "bg-bg-elevated border border-border-subtle"
          }`}
          aria-label={i < filled ? "Model agrees" : "Model disagrees"}
        />
      ))}
    </div>
  )
}

/** Horizontal CI bar — shows the 80% range with current-price marker.
 *  Visual cue: narrow band = tight ensemble consensus, wide = uncertain. */
function CIRangeBar({
  current,
  lower,
  upper,
  median,
}: {
  current: number
  lower: number
  upper: number
  median: number
}) {
  // Normalize to 0..100 using bar bounds padded 5% beyond [lower, upper]
  // so current-price marker has room even when outside CI.
  const bandMin = Math.min(current, lower) * 0.98
  const bandMax = Math.max(current, upper) * 1.02
  const range = bandMax - bandMin || 1
  const pct = (v: number) => Math.max(0, Math.min(100, ((v - bandMin) / range) * 100))

  const lowerPct = pct(lower)
  const upperPct = pct(upper)
  const medianPct = pct(median)
  const currentPct = pct(current)

  return (
    <div className="relative h-4 w-full rounded-full bg-bg-elevated">
      {/* CI band */}
      <div
        className="absolute top-1 bottom-1 rounded-full bg-gradient-to-r from-[var(--accent-from)]/30 via-[var(--accent-from)]/50 to-[var(--accent-to)]/30"
        style={{ left: `${lowerPct}%`, width: `${upperPct - lowerPct}%` }}
      />
      {/* Median marker */}
      <div
        className="absolute top-0 bottom-0 w-0.5 bg-[var(--accent-from)]"
        style={{ left: `${medianPct}%` }}
        title={`Predicted median: $${median.toFixed(2)}`}
      />
      {/* Current price marker */}
      <div
        className="absolute -top-0.5 -bottom-0.5 w-px bg-text-primary"
        style={{ left: `${currentPct}%` }}
        title={`Current: $${current.toFixed(2)}`}
      >
        <div className="absolute left-1/2 top-0 h-1 w-1 -translate-x-1/2 rounded-full bg-text-primary" />
      </div>
    </div>
  )
}

function ReturnCell({ label, value }: { label: string; value: number | null }) {
  const v = value ?? 0
  const positive = v > 0
  return (
    <div>
      <p className="text-[10px] uppercase tracking-wider text-text-muted">{label}</p>
      <p className={`mt-0.5 font-mono text-sm font-medium ${positive ? "text-success" : "text-danger"}`}>
        {positive ? "+" : ""}
        {v.toFixed(2)}%
      </p>
    </div>
  )
}

function AlphaSignalsPaywall() {
  return (
    <div className="mx-auto max-w-2xl">
      <div className="rounded-card border border-border-subtle bg-bg-surface p-8 text-center">
        <div className="mx-auto mb-4 flex size-12 items-center justify-center rounded-full bg-gradient-to-br from-[var(--accent-from)]/20 to-[var(--accent-to)]/20">
          <Lock className="size-5 text-[var(--accent-from)]" />
        </div>
        <h1 className="font-heading text-2xl font-semibold">Alpha Signals</h1>
        <p className="mx-auto mt-3 max-w-md text-sm text-text-secondary">
          Premium Pro feature — high-conviction signals generated by a 3-model ensemble consensus.
          Historical back-test shows{" "}
          <span className="text-success font-medium">Sharpe {MODEL_METRICS.conflong_sharpe}</span>{" "}
          and{" "}
          <span className="text-success font-medium">
            {MODEL_METRICS.conflong_win_rate_pct}% win rate
          </span>
          .
        </p>

        <div className="my-6 grid grid-cols-3 gap-3 text-xs">
          <div className="rounded-button border border-border-subtle bg-bg-elevated/50 p-3">
            <p className="font-mono text-lg font-semibold text-success">
              {MODEL_METRICS.conflong_sharpe}
            </p>
            <p className="mt-0.5 text-text-muted">Sharpe</p>
          </div>
          <div className="rounded-button border border-border-subtle bg-bg-elevated/50 p-3">
            <p className="font-mono text-lg font-semibold text-success">
              {MODEL_METRICS.conflong_win_rate_pct}%
            </p>
            <p className="mt-0.5 text-text-muted">Win Rate</p>
          </div>
          <div className="rounded-button border border-border-subtle bg-bg-elevated/50 p-3">
            <p className="font-mono text-lg font-semibold">3</p>
            <p className="mt-0.5 text-text-muted">Models</p>
          </div>
        </div>

        <Link href="/billing">
          <Button variant="gradient" size="lg" className="gap-2">
            Upgrade to Pro
            <ArrowUpRight className="size-4" />
          </Button>
        </Link>

        <p className="mt-4 text-[11px] text-text-muted">
          Back-test based on {MODEL_METRICS.conflong_n_trades} trades in single test window — past performance not indicative of future results.
        </p>
      </div>
    </div>
  )
}
